SELECT city, LENGTH(city)
FROM STATION
WHERE LENGTH(city) LIKE (
    SELECT MIN(LENGTH(city))
    FROM STATION
)
ORDER BY city
LIMIT 1;

SELECT city, LENGTH(city)
FROM STATION
WHERE LENGTH(city) LIKE (
    SELECT MAX(LENGTH(city))
    FROM STATION
)
ORDER BY city
LIMIT 1;